### ISSUE TITLE
Tag Page don't work

### ISSUE THREAD

**Issue by fistwho** [huangyuzhang/Fizzy-Theme#69]
Hey Simon thank you for your amazing theme. I hope you can help. 

I try to setup the Tag Page i add a page named Topics and the url is /tags/ and use the template Tag-Archive. But no Topics will shown. I check the logs and found a SQLite Error. 

```
[2021-10-28 09:02:41] ERROR Could not understand request.,
Could not understand request.,
Error ID:,
    ce567a40-37cd-11ec-8f45-8975602ff55e,
Error Code: ,
    SQLITE_ERROR,
BadRequestError: Could not understand request.,
    at /var/lib/ghost/versions/4.20.3/node_modules/@tryghost/bookshelf-pagination/lib/bookshelf-pagination.js:258:27,
----------------------------------------,
    at async Function.findPage (/var/lib/ghost/versions/4.20.3/core/server/models/base/plugins/crud.js:99:30),
Error: select `tags`.* from `tags` where `tags`.`tags` not in ('getting-started') and `tags`.`id` in (select distinct `posts_tags`.`tag_id` from `posts_tags` inner join `posts` on `posts`.`id` = `posts_tags`.`post_id` where posts_tags.tag_id = tags.id and `posts`.`status` = 'published') order by `tags`.`name` ASC - SQLITE_ERROR: no such column: tags.tags,
[2021-10-28 09:02:41] INFO "GET /tags/" 200 74ms
```

I use the latest Version of Ghost. 

Greets ;)

**Comment by afeng616** [comment]
So how can u handle the error in the tags page?

**Comment by HackTheBamboo** [comment]
Hello

To correct this problem, you must remove the filter.

filter="tags:-[getting-started]"
